services:
  command.bus:
    class: EventBus\CommandBus\CommandBus
    arguments:
      - "@service_container"
      - "@bus.options.resolver"
  bus.options.resolver:
    class: EventBus\BusOptionsResolver
  query.bus:
    class: EventBus\QueryBus\QueryBus
    arguments:
      - "@service_container"
      - "@bus.options.resolver"