services:
  _defaults:
    public: true
  Bruli\EventBusBundle\CommandBus\CommandBus:
    arguments:
      $container: "@service_container"
      $optionsResolver: '@Bruli\EventBusBundle\BusOptionsResolver'
  Bruli\EventBusBundle\BusOptionsResolver:
  Bruli\EventBusBundle\QueryBus\QueryBus:
    arguments:
      $container: "@service_container"
      $optionsResolver: '@Bruli\EventBusBundle\BusOptionsResolver'

  bruli.command.bus: '@Bruli\EventBusBundle\CommandBus\CommandBus'
  bruli.bus.options.resolver: '@Bruli\EventBusBundle\BusOptionsResolver'
  bruli.query.bus: '@Bruli\EventBusBundle\QueryBus\QueryBus'